CREATE TABLE CATEGORY (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(32) NOT NULL,
  DESCRIPTION VARCHAR(128) NOT NULL
);

CREATE TABLE APPARITION (
  ID SERIAL PRIMARY KEY,
  TITLE VARCHAR(64) NOT NULL,
  DESCRIPTION VARCHAR(512) NOT NULL,
  DATE VARCHAR(32) NOT NULL,
  LOCATION VARCHAR(64) NOT NULL
);
